name: momentum
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: 3.3.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: 2.0.3+1
  path: 1.8.2
  path_provider: 2.0.11
  uuid: 3.0.6
  go_router: 4.4.1
  carousel_slider: 4.1.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/confetti.gif
